### ISSUE TITLE
Crash when connecting any two types of coil.

### ISSUE THREAD

**Issue by davidgarland** [gunnerwolf/TeslaCoils#12]
[11:36:29] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/28/16 11:36 AM
Description: Rendering Block Entity

java.lang.AbstractMethodError: com.skidsdev.teslacoils.tile.TileEntityRelayCoil.getPos()Lnet/minecraft/util/math/BlockPos;
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.renderLaser(TESRRelayCoil.java:67)
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.renderTileEntityAt(TESRRelayCoil.java:30)
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.func_180535_a(TESRRelayCoil.java:21)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:700)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.renderLaser(TESRRelayCoil.java:67)
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.renderTileEntityAt(TESRRelayCoil.java:30)
    at com.skidsdev.teslacoils.tile.tesr.TESRRelayCoil.func_180535_a(TESRRelayCoil.java:21)

-- Block Entity Details --
Details:
    Name: relaycoil // com.skidsdev.teslacoils.tile.TileEntityRelayCoil
    Block type: ID #247 (tile.teslacoils:blockRelayCoil // com.skidsdev.teslacoils.block.BlockRelayCoil)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (50,4,64), Chunk: (at 2,0,0 in 3,4; contains blocks 48,0,64 to 63,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #247 (tile.teslacoils:blockRelayCoil // com.skidsdev.teslacoils.block.BlockRelayCoil)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:700)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['<PROFILE NAME>'/85, l='MpServer', x=48.54, y=4.00, z=64.91]]
    Chunk stats: MultiplayerChunkCache: 579, 579
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (58,4,61), Chunk: (at 10,0,13 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 3408 game time, 3408 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 54 total; [EntitySlime['Slime'/74498, l='MpServer', x=-17.89, y=4.00, z=-3.34], EntitySlime['Slime'/6, l='MpServer', x=-14.31, y=4.75, z=32.20], EntitySlime['Slime'/9225, l='MpServer', x=-20.90, y=4.00, z=134.66], EntitySlime['Slime'/13, l='MpServer', x=-25.83, y=4.00, z=22.33], EntitySlime['Slime'/14, l='MpServer', x=-13.06, y=5.25, z=45.67], EntitySlime['Slime'/15, l='MpServer', x=-23.07, y=5.17, z=44.54], EntitySlime['Slime'/16, l='MpServer', x=-31.40, y=4.00, z=74.48], EntitySlime['Slime'/17, l='MpServer', x=0.73, y=4.00, z=105.81], EntitySlime['Slime'/19, l='MpServer', x=-17.92, y=4.00, z=129.31], EntityPig['Pig'/21, l='MpServer', x=-15.87, y=4.00, z=-7.29], EntitySlime['Slime'/41877, l='MpServer', x=-26.43, y=5.08, z=136.29], EntityPig['Pig'/22, l='MpServer', x=-4.56, y=4.00, z=-12.66], EntityPig['Pig'/23, l='MpServer', x=-9.73, y=4.00, z=-7.03], EntityPig['Pig'/24, l='MpServer', x=-11.37, y=4.00, z=-7.00], EntityPig['Pig'/25, l='MpServer', x=-14.04, y=4.00, z=-10.77], EntitySlime['Slime'/27, l='MpServer', x=-2.91, y=4.50, z=40.87], EntitySlime['Slime'/28, l='MpServer', x=30.65, y=4.00, z=56.57], EntityCow['Cow'/29, l='MpServer', x=-10.50, y=4.00, z=133.50], EntitySlime['Slime'/30, l='MpServer', x=1.06, y=4.00, z=7.33], EntitySlime['Slime'/31, l='MpServer', x=15.92, y=4.00, z=-4.08], EntitySlime['Slime'/27679, l='MpServer', x=67.25, y=4.00, z=30.04], EntitySlime['Slime'/32, l='MpServer', x=2.60, y=4.50, z=18.98], EntitySlime['Slime'/33, l='MpServer', x=0.12, y=4.00, z=18.27], EntitySlime['Slime'/35, l='MpServer', x=34.12, y=4.00, z=121.90], EntitySlime['Slime'/36, l='MpServer', x=23.63, y=4.00, z=136.43], EntitySlime['Slime'/37, l='MpServer', x=32.49, y=4.00, z=133.35], EntitySlime['Slime'/38, l='MpServer', x=36.17, y=4.80, z=132.80], EntitySlime['Slime'/39, l='MpServer', x=56.48, y=4.42, z=85.16], EntityPig['Pig'/42, l='MpServer', x=64.36, y=4.00, z=-2.78], EntityPig['Pig'/43, l='MpServer', x=64.17, y=4.00, z=-10.00], EntitySheep['Sheep'/44, l='MpServer', x=47.63, y=4.00, z=-9.39], EntitySlime['Slime'/45, l='MpServer', x=46.37, y=5.00, z=24.07], EntitySlime['Slime'/47, l='MpServer', x=78.14, y=4.00, z=51.16], EntitySlime['Slime'/48, l='MpServer', x=50.88, y=4.80, z=91.61], EntitySlime['Slime'/49, l='MpServer', x=47.72, y=4.00, z=89.96], EntitySlime['Slime'/50, l='MpServer', x=68.48, y=5.25, z=107.20], EntitySlime['Slime'/51, l='MpServer', x=62.20, y=4.00, z=101.29], EntitySlime['Slime'/56895, l='MpServer', x=70.80, y=4.95, z=18.72], EntityCow['Cow'/64, l='MpServer', x=76.28, y=4.00, z=-11.65], EntitySheep['Sheep'/65, l='MpServer', x=70.83, y=4.00, z=-12.78], EntitySlime['Slime'/66, l='MpServer', x=74.75, y=4.00, z=22.72], EntitySlime['Slime'/67, l='MpServer', x=55.97, y=4.12, z=32.17], EntitySlime['Slime'/17091, l='MpServer', x=121.84, y=4.00, z=139.92], EntitySlime['Slime'/68, l='MpServer', x=73.31, y=4.00, z=74.05], EntitySlime['Slime'/69, l='MpServer', x=62.01, y=4.00, z=73.19], EntitySlime['Slime'/70, l='MpServer', x=75.31, y=4.00, z=101.31], EntitySlime['Slime'/17738, l='MpServer', x=-24.58, y=4.95, z=73.20], EntityPlayerSP['<PROFILE NAME>'/85, l='MpServer', x=48.54, y=4.00, z=64.91], EntityPig['Pig'/80, l='MpServer', x=122.86, y=4.00, z=141.10], EntitySlime['Slime'/67931, l='MpServer', x=22.91, y=4.00, z=136.70], EntitySlime['Slime'/94947, l='MpServer', x=59.78, y=4.00, z=22.72], EntitySlime['Slime'/12788, l='MpServer', x=55.59, y=5.17, z=27.69], EntitySlime['Slime'/64376, l='MpServer', x=-9.05, y=4.00, z=13.22], EntitySlime['Slime'/3579, l='MpServer', x=48.35, y=4.00, z=99.15]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Mac OS X (x86_64) version 10.11.6
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 386225600 bytes (368 MB) / 770179072 bytes (734 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -Xms512m -Xmx1024m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2075 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2075-universal.jar) 
    UCHIJAAAA   Forge{12.18.1.2075} [Minecraft Forge](forge-1.10.2-12.18.1.2075-universal.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.8} [Extreme Reactors](ExtremeReactors-1.9.4-0.4.5.8.jar) 
    UCHIJAAAA   JEI{3.9.0.246} [Just Enough Items](jei_1.10.2-3.9.0.246.jar) 
    UCHIJAAAA   mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJAAAA   tesla{1.2.1.46} [TESLA](Tesla-1.10.2-1.2.1.46.jar) 
    UCHIJAAAA   teslacoils{v0.2.1.0} [Tesla Coils](teslacoils-0.2.1.0.jar) 
    Loaded coremods (and transformers): 
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.42.15, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
```

[11:36:29] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/T3SL4/minecraft/crash-reports/crash-2016-08-28_11.36.29-client.txt
Exception in thread "Client Shutdown Thread" AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

**Comment by dylanrenwick** [comment]
What version of Tesla Coils are you using? This was fixed a few versions back.

**Comment by davidgarland** [comment]
@gunnerwolf: 0.2.1.0. I downloaded it off of CurseForge, pretty sure it's the latest one on there.

**Comment by dylanrenwick** [comment]
Fixed in latest PR, new version will be pushed out in the next couple of days

**Comment by davidgarland** [comment]
Thanks! The mod looks awesome and I can't wait to be able to use it. =]
